apiVersion: v2
name: microservices
description: A Helm chart for deploying the PINFO microservice architecture
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: postgresql
    version: 7.7.2
    repository: https://charts.helm.sh/stable
    alias: counterparty-db
  - name: postgresql
    version: 7.7.2
    repository: https://charts.helm.sh/stable
    alias: instrument-db
  - name: ingress-nginx 
    alias: main-ingress
    version: 3.30.0
    repository: https://kubernetes.github.io/ingress-nginx
  - name: kafka 
    version: 7.2.9
    repository: https://charts.bitnami.com/bitnami    
