apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
        component: oauth2-proxy
    spec:
      containers:
      - image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4180
          protocol: TCP        
        name: oauth2-proxy
        args:
        - --provider=oidc
        - --upstream=https://pinfo.westeurope.cloudapp.azure.com/
        - --http-address=0.0.0.0:4180
        - --cookie-secure=true
        - --redirect-url=https://pinfo.westeurope.cloudapp.azure.com/oauth2/callback
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --pass-authorization-header=true
        - --cookie-secure=true
        - --skip-auth-preflight=false
        - --skip-oidc-discovery
        - --oidc-issuer-url={{ required "Base URL of oauth server is required" .Values.oauth.baseUrl }}
        - --login-url={{ required "Base URL of oauth server is required" .Values.oauth.baseUrl }}authorize
        - --redeem-url={{ required "Base URL of oauth server is required" .Values.oauth.baseUrl }}oauth/token
        - --oidc-jwks-url={{ .Values.oauth.baseUrl }}.well-known/jwks.json
        - --email-domain=*
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ required "Oauth client Id is required" .Values.oauth.clientId  }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: {{ required "Oauth secret is required" .Values.oauth.secret }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: LjWWb+S41ihgZwhO5mwsQQ==
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
